# -*- coding: utf-8 -*-
"""GovernancePolicy — builtin_rules + user_rules two-layer policy engine.

- builtin_rules + user_rules two layers:
    builtin_rules — system built-in protection (resource ask / command deny), not modifiable by agent
    user_rules    — generated by user/approve, can be added or removed
- Evaluation flow: ToolRegistry type check → builtin_rules → user_rules → global fallback
- Rule generalization: smart generalization on approve (first token + *), high-risk commands stay exact
"""
from __future__ import annotations
import copy
from dataclasses import dataclass, field
from enum import Enum
from fnmatch import fnmatch
from pathlib import Path
from typing import Any, List, Optional

import yaml

from .tool_registry import ToolRegistry, DEFAULT_REGISTRY
from ..sandbox import SandboxConfig

# ---------------------------------------------------------------------------
# Core types
# ---------------------------------------------------------------------------

class GovernanceAction(str, Enum):
    ALLOW = "allow"
    DENY = "deny"
    ASK = "ask"
    # bash tool with no hit → sandbox fallback
    SANDBOX_FALLBACK = "sandbox_fallback"


@dataclass
class GovernanceDecision:
    action: GovernanceAction
    reason: str
    sandbox_config: SandboxConfig | None = None


class ToolCallSpec:
    """Specification of a tool call (used by the governor for evaluation).

    Attributes:
        tool_name: Tool name, e.g. "Read", "Bash", "Write"
        target: Tool's target argument, e.g. "src/main.py", "git push"
        agent_id: Agent ID that initiated the call
        session_id: Current session ID
    """

    def __init__(self, tool_name: str, target: str,
                 agent_id: str, session_id: str) -> None:
        self.tool_name = tool_name
        self.target = target
        self.agent_id = agent_id
        self.session_id = session_id


@dataclass
class GovernanceRule:
    """Unified policy rule.

    match format: "ToolName(pattern)"
        - ToolName: Read, Write, Bash, Browser, etc.; "*" matches all tools
        - pattern: glob pattern matched against the tool's target argument

    Examples:
        GovernanceRule(match="Bash(git *)", action=GovernanceAction.ALLOW)
        GovernanceRule(match="Write(.env*)", action=GovernanceAction.DENY)
        GovernanceRule(match="*(.ssh/**)", action=GovernanceAction.ASK)   # all tools
        GovernanceRule(match="Read(src/**)", action=GovernanceAction.ALLOW,
                   grantee="agent-abc", duration="session")

    Action semantics vary by tool type:
        Explicit-resource tools:
            allow → execute directly (no sandbox)
            deny  → reject
            ask   → ask user, execute directly after approval
        Bash-type tools:
            allow → execute in sandbox (pre-authorized, no violation expected)
            deny  → reject (no sandbox)
            ask   → ask user, execute in sandbox after approval
    """
    match: str                              # "ToolName(pattern)"
    action: GovernanceAction = GovernanceAction.DENY
    reason: str = ""                        # Rule description
    grantee: str = "*"                      # Authorized subject
    duration: str = "permanent"             # "session" | "permanent"
    session_id: Optional[str] = None        # Chat session ID

    def _globmatch(self, pattern: str, target: str) -> bool:
        """wcmatch globmatch with directory self-match support."""
        from wcmatch import glob
        flags = glob.GLOBSTAR | glob.BRACE | glob.NEGATE | glob.SPLIT
        if glob.globmatch(target, pattern, flags=flags):
            return True
        if pattern.endswith("/**"):
            dir_pattern = pattern[:-3]
            if glob.globmatch(target, dir_pattern, flags=flags):
                return True
        return False

    def matches_tool_call(self, tc_spec: ToolCallSpec,
                          tool_type: str = "") -> bool:
        """Determine whether this rule matches the given tool call.

        Matching logic:
            1. grantee match ("*" matches all)
            2. session-level rule: session_id must match
            3. Parse self.match into (rule_tool, rule_pattern)
            4. If rule_tool is "*" it matches all tools
            5. Glob match target against rule_pattern
               - For "*" rules + shell tool, additional substring matching
                 (command may contain sensitive file paths, e.g. "cat .env")

        Note: caller is responsible for resolving target to absolute path
              (WORKSPACE_DIR replacement is done at load time).
        """
        # grantee check
        if self.grantee != "*" and self.grantee != tc_spec.agent_id:
            return False
        # session-level rule: bound to a specific chat session
        if self.duration == "session" and self.session_id and tc_spec.session_id:
            if self.session_id != tc_spec.session_id:
                return False
        # parse "ToolName(pattern)"
        rule_tool, rule_pattern = _parse_match(self.match)
        # "*" matches all tools (used for builtin resource protection)
        if rule_tool != "*" and rule_tool != tc_spec.tool_name:
            return False
        is_wildcard = rule_tool == "*"

        use_globmatch = is_wildcard or tool_type == "file"

        if use_globmatch:
            return self._globmatch(rule_pattern, tc_spec.target)
        else:
            return fnmatch(tc_spec.target, rule_pattern)


# ---------------------------------------------------------------------------
# builtin_rules
# ---------------------------------------------------------------------------

DEFAULT_BUILTIN_RULES: List[GovernanceRule] = [
    # ── Resource protection (any tool access requires user confirmation) ──
    GovernanceRule(
        match="*(**/.env*)",
        action=GovernanceAction.ASK,
        reason="Env file may contain secrets/credentials",
    ),
    GovernanceRule(
        match="*(**/.ssh/**)",
        action=GovernanceAction.ASK,
        reason="SSH credentials directory",
    ),
    GovernanceRule(
        match="*(**/*.pem)",
        action=GovernanceAction.ASK,
        reason="Private key file",
    ),
    GovernanceRule(
        match="*(**/*.key)",
        action=GovernanceAction.ASK,
        reason="Private key file",
    ),
    GovernanceRule(
        match="*(**/*.p12)",
        action=GovernanceAction.ASK,
        reason="PKCS#12 certificate bundle",
    ),
    GovernanceRule(
        match="*(**/*.pfx)",
        action=GovernanceAction.ASK,
        reason="PKCS#12 certificate bundle",
    ),
    GovernanceRule(
        match="*(**/.aws/**)",
        action=GovernanceAction.ASK,
        reason="AWS credentials directory",
    ),
    GovernanceRule(
        match="*(**/.gnupg/**)",
        action=GovernanceAction.ASK,
        reason="GPG keys directory",
    ),
    GovernanceRule(
        match="*(**/.kube/**)",
        action=GovernanceAction.ASK,
        reason="Kubernetes config directory",
    ),
    GovernanceRule(
        match="*(**/.netrc)",
        action=GovernanceAction.ASK,
        reason="Netrc login credentials file",
    ),
    GovernanceRule(
        match="*(**/.npmrc)",
        action=GovernanceAction.ASK,
        reason="npm auth token file",
    ),
    GovernanceRule(
        match="*(**/.pypirc)",
        action=GovernanceAction.ASK,
        reason="PyPI API token file",
    ),
    # ── High-risk commands (hard wall, never allowed) ──
    GovernanceRule(
        match="Bash(rm * -rf *//*)",
        action=GovernanceAction.DENY,
        reason="Root filesystem deletion",
    ),
    GovernanceRule(
        match="Bash(sudo *)",
        action=GovernanceAction.DENY,
        reason="Privilege escalation prohibited",
    ),
]


# ---------------------------------------------------------------------------
# Default sandbox deny_paths — paths forbidden for sandbox processes
# ---------------------------------------------------------------------------

DEFAULT_ENV_BLACKLIST: List[str] = [
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_ACCESS_KEY_ID",
]


DEFAULT_SANDBOX_DENY_PATHS: List[str] = [
    # SSH keys and config
    "~/.ssh",
    # AWS credentials
    "~/.aws",
    # GPG keys
    "~/.gnupg",
    # Kubernetes config
    "~/.kube",
    # Google Cloud credentials
    "~/.config/gcloud",
    # Azure CLI credentials
    "~/.azure",
    # Docker auth config
    "~/.docker/config.json",
    # Generic env files (may contain secrets)
    "~/.env",
    # Claude Code config & memory
    "~/.claude",
    # macOS Keychain database
    "~/Library/Keychains",
    # Browser credentials
    "~/Library/Application Support/Google/Chrome/Default/Login Data",
    "~/Library/Application Support/Firefox/Profiles",
    # Git credentials
    "~/.git-credentials",
    "~/.gitconfig",  # may contain tokens in URL
    # Terraform state (may contain sensitive outputs)
    "~/.terraformrc",
    # HashiCorp Vault token
    "~/.vault-token",
    # npm / yarn auth tokens
    "~/.npmrc",
    "~/.yarnrc",
    # pip / PyPI API tokens
    "~/.pypirc",
    # Other common sensitive configs
    "~/.config/gh",   # GitHub CLI
    "~/.config/nix",  # Nix config
    "~/.netrc",       # generic login credentials
]

FILE_READ_TOOLS: frozenset[str] = frozenset({"Read", "ViewImage", "ViewVideo", "SendFileToUser"})
FILE_WRITE_TOOLS: frozenset[str] = frozenset({"Write", "Edit", "Append"})


# ---------------------------------------------------------------------------
# Default user_rules (for cold start)
# ---------------------------------------------------------------------------

DEFAULT_USER_RULES: List[GovernanceRule] = [
    # ── Internal tools (no side effects, always allowed) ──
    GovernanceRule(match="GetCurrentTime(*)", action=GovernanceAction.ALLOW,
               reason="Read-only system tool"),
    GovernanceRule(match="GetTokenUsage(*)", action=GovernanceAction.ALLOW,
               reason="Read-only usage query"),
    GovernanceRule(match="ListAgents(*)", action=GovernanceAction.ALLOW,
               reason="Read-only agent list"),
    GovernanceRule(match="ChatWithAgent(*)", action=GovernanceAction.ALLOW,
               reason="Inter-agent messaging"),
    GovernanceRule(match="SubmitToAgent(*)", action=GovernanceAction.ALLOW,
               reason="Inter-agent task submission"),
    GovernanceRule(match="CheckAgentTask(*)", action=GovernanceAction.ALLOW,
               reason="Read-only task status query"),
    GovernanceRule(match="DelegateExternalAgent(*)", action=GovernanceAction.ALLOW,
               reason="Inter-agent delegation"),
    # ── File tools (operations within WORKSPACE_DIR, always allowed) ──
    GovernanceRule(match="Read(WORKSPACE_DIR/**)", action=GovernanceAction.ALLOW,
               reason="File read within workspace"),
    GovernanceRule(match="Write(WORKSPACE_DIR/**)", action=GovernanceAction.ALLOW,
               reason="File write within workspace"),
    GovernanceRule(match="Edit(WORKSPACE_DIR/**)", action=GovernanceAction.ALLOW,
               reason="File edit within workspace"),
    GovernanceRule(match="Append(WORKSPACE_DIR/**)", action=GovernanceAction.ALLOW,
               reason="File append within workspace"),
    GovernanceRule(match="Grep(WORKSPACE_DIR/**)", action=GovernanceAction.ALLOW,
               reason="Content search within workspace"),
    GovernanceRule(match="Glob(WORKSPACE_DIR/**)", action=GovernanceAction.ALLOW,
               reason="File listing within workspace"),
    # ── Browser (treat as always allowed for now) ──
    GovernanceRule(match="Browser(**)", action=GovernanceAction.ALLOW,
               reason="Allow all browser access"),
]


# ---------------------------------------------------------------------------
# GovernancePolicy
# ---------------------------------------------------------------------------

@dataclass
class GovernancePolicy:
    """Policy: builtin_rules + user_rules two layers, first-match-wins.

    Loaded from policy_dir/policy.yaml, held by ResourceGovernor.

    Evaluation flow (§5):
        ToolRegistry type check → builtin_rules → user_rules → global fallback

    Lifecycle:
        load → evaluate (hot path) → add_rule (user approve) → save
    """
    version: str = "1.0"
    builtin_rules: List[GovernanceRule] = field(default_factory=list)
    user_rules: List[GovernanceRule] = field(default_factory=list)
    env_blacklist: List[str] = field(default_factory=list)
    audit_level: str = "all"       # "all" | "write_only" | "none"

    # Internal reference to registry (defaults to module-level DEFAULT_REGISTRY)
    _registry: ToolRegistry = field(
        default=None, repr=False, compare=False,
    )

    def __post_init__(self) -> None:
        if self._registry is None:
            self._registry = DEFAULT_REGISTRY

    # ------------------------------------------------------------------
    # Read-only view
    # ------------------------------------------------------------------

    @property
    def rules(self) -> List[GovernanceRule]:
        """Merge builtin_rules + user_rules (read-only snapshot).

        Note: returns a snapshot; modifications will not affect the original list.
        Use add_rule() to add new rules.
        """
        return list(self.builtin_rules) + list(self.user_rules)

    def evaluate(
        self, tc_spec: ToolCallSpec,
    ) -> GovernanceDecision:
        """Evaluate policy decision for a tool call.

        Evaluation flow (§5):
            0. ToolRegistry type check: unknown → DENY, internal → ALLOW
            1. builtin_rules first-match-wins
            2. user_rules first-match-wins
            3. Global fallback: shell → SANDBOX_FALLBACK, others → ASK

        Returns: GovernanceDecision
        """
        # ── Step 0: ToolRegistry type check ──
        tool_type = self._registry.get_type(tc_spec.tool_name)
        if tool_type == "unknown":
            return GovernanceDecision(
                action=GovernanceAction.DENY,
                reason=f"Unregistered tool: {tc_spec.tool_name}",
            )
        if tool_type == "internal":
            return GovernanceDecision(action=GovernanceAction.ALLOW, reason="")

        # ── Step 1: builtin_rules ──
        for rule in self.builtin_rules:
            if rule.matches_tool_call(
                tc_spec, tool_type=tool_type,
            ):
                return GovernanceDecision(
                    action=GovernanceAction(rule.action.value),
                    reason=rule.reason,
                )

        # ── Step 2: user_rules ──
        for rule in self.user_rules:
            if rule.matches_tool_call(
                tc_spec, tool_type=tool_type,
            ):
                return GovernanceDecision(
                    action=GovernanceAction(rule.action.value),
                    reason=rule.reason,
                )

        # ── Step 3: Global fallback ──
        if tool_type == "shell":
            return GovernanceDecision(
                action=GovernanceAction.SANDBOX_FALLBACK,
                reason="sandbox fallback",
            )
        return GovernanceDecision(action=GovernanceAction.ASK, reason="No rule hit")

    def evaluate_source(self, tc_spec: ToolCallSpec) -> str:
        """Determine which rule source a tool call matches.

        Returns:
            "builtin"  — matched builtin_rules (no rule recorded on approve)
            "user"     — matched user_rules (rule can be recorded on approve)
            "fallback" — no match, global fallback
        """
        tool_type = self._registry.get_type(tc_spec.tool_name)
        for rule in self.builtin_rules:
            if rule.matches_tool_call(
                tc_spec, tool_type=tool_type,
            ):
                return "builtin"
        for rule in self.user_rules:
            if rule.matches_tool_call(
                tc_spec, tool_type=tool_type,
            ):
                return "user"
        return "fallback"

    # ------------------------------------------------------------------
    # Dynamic mutation (only operates on user_rules)
    # ------------------------------------------------------------------

    def add_rule(self, rule: GovernanceRule) -> None:
        """Prepend a rule to user_rules (called after user approval).

        New rules are inserted at the beginning so they take priority
        (first-match-wins evaluation). This ensures a newly added DENY
        can override an earlier ALLOW (e.g. Browser(**) → ALLOW).

        Note: builtin_rules are read-only and cannot be modified via this method.
        """
        self.user_rules.insert(0, rule)

    def remove_rule(self, index: int) -> None:
        """Remove a rule from user_rules (Console UI / admin operation).

        Note: builtin_rules cannot be deleted via this method.
        """
        if 0 <= index < len(self.user_rules):
            self.user_rules.pop(index)


# ---------------------------------------------------------------------------
# Rule generalization
# ---------------------------------------------------------------------------

def generalize_rule_match(tool_name: str, target: str) -> str:
    """Construct a match string from an approved rule.

    Current strategy: no generalization, always record exact match
    to avoid security risks from wildcards.

    Args:
        tool_name: policy tool name, e.g. "Bash"
        target: tool's target argument value

    Returns:
        match string, e.g. "Bash(git status)"
    """
    return f"{tool_name}({target})"


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def _parse_match(match_str: str) -> tuple[str, str]:
    """Parse "ToolName(pattern)" → (tool_name, pattern).

    Uses index to find the first "(", since the tool name never contains "(".
    Uses rindex to find the last ")" to handle cases where pattern contains ")".
    Example: "Bash(git *)" → ("Bash", "git *")
             "*(.env*)"   → ("*", ".env*")      # wildcard for all tools
             "Read(src/**)" → ("Read", "src/**")
             "Bash(echo $(date))" → ("Bash", "echo $(date)")
    """
    paren = match_str.index("(")
    close = match_str.rindex(")")
    tool_name = match_str[:paren]
    pattern = match_str[paren + 1:close]
    return tool_name, pattern


# ---------------------------------------------------------------------------
# Load / persist
# ---------------------------------------------------------------------------

def load_governance_policy(policy_dir: str, workspace_dir: str) -> GovernancePolicy:
    """Load from policy_dir/policy.yaml; return default policy if missing.

    Args:
        policy_dir: directory containing policy.yaml
        workspace_dir: used to replace WORKSPACE_DIR placeholders in rules

    YAML format:
        version: "1.0"
        audit_level: "all"
        builtin_rules:
          - match: "*(.env*)"
            action: ask
            reason: "Env file may contain secrets/credentials"
        user_rules:
          - match: "Read(WORKSPACE_DIR/*)"
            action: allow
    """
    path = Path(policy_dir) / "policy.yaml"
    if not path.exists():
        return _create_default_policy(workspace_dir)

    try:
        with open(path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
    except Exception:
        return _create_default_policy(workspace_dir)

    if not isinstance(data, dict):
        return _create_default_policy(workspace_dir)

    version = data.get("version", "1.0")
    audit_level = data.get("audit_level", "all")

    # ── builtin_rules + user_rules ──
    builtin_rules = _parse_rules(data.get("builtin_rules", []))
    user_rules = _parse_rules(data.get("user_rules", []))

    # ── env_blacklist ──
    env_blacklist = data.get("env_blacklist", [])
    if not isinstance(env_blacklist, list):
        env_blacklist = []

    # ── Cold start: fill in missing default rules ──
    if not builtin_rules:
        builtin_rules = copy.deepcopy(DEFAULT_BUILTIN_RULES)
    if not user_rules:
        user_rules = copy.deepcopy(DEFAULT_USER_RULES)
    if not env_blacklist:
        env_blacklist = list(DEFAULT_ENV_BLACKLIST)

    # ── Replace WORKSPACE_DIR with actual path ──
    if workspace_dir:
        _resolve_workspace_dir(builtin_rules, workspace_dir)
        _resolve_workspace_dir(user_rules, workspace_dir)

    return GovernancePolicy(
        version=version,
        builtin_rules=builtin_rules,
        user_rules=user_rules,
        env_blacklist=env_blacklist,
        audit_level=audit_level,
    )


def save_governance_policy(policy: GovernancePolicy, policy_dir: str,
                           workspace_dir: str = "") -> None:
    """Write policy.yaml.

    Args:
        policy: policy to persist
        policy_dir: directory to write policy.yaml
        workspace_dir: workspace path, used to restore actual paths back to
                       WORKSPACE_DIR placeholders (keeps yaml portable)
    """
    builtin_rules = list(policy.builtin_rules)
    user_rules = list(policy.user_rules)

    # ── Restore actual paths to WORKSPACE_DIR placeholders ──
    if workspace_dir:
        _unresolve_workspace_dir(builtin_rules, workspace_dir)
        _unresolve_workspace_dir(user_rules, workspace_dir)

    path = Path(policy_dir) / "policy.yaml"
    data = {
        "version": policy.version,
        "audit_level": policy.audit_level,
        "env_blacklist": list(policy.env_blacklist),
        "builtin_rules": [
            _rule_to_dict(r) for r in builtin_rules
        ],
        "user_rules": [
            _rule_to_dict(r) for r in user_rules
        ],
    }

    with open(path, "w", encoding="utf-8") as f:
        yaml.dump(data, f, default_flow_style=False,
                  allow_unicode=True, sort_keys=False)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _create_default_policy(workspace_dir: str = "") -> GovernancePolicy:
    """Create a policy with full default rules (cold start)."""
    import copy
    builtin_rules = copy.deepcopy(DEFAULT_BUILTIN_RULES)
    user_rules = copy.deepcopy(DEFAULT_USER_RULES)
    if workspace_dir:
        _resolve_workspace_dir(builtin_rules, workspace_dir)
        _resolve_workspace_dir(user_rules, workspace_dir)
    return GovernancePolicy(
        version="1.0",
        builtin_rules=builtin_rules,
        user_rules=user_rules,
        env_blacklist=list(DEFAULT_ENV_BLACKLIST),
    )


def _resolve_workspace_dir(rules: List[GovernanceRule], workspace_dir: str):
    """Replace WORKSPACE_DIR in rules with actual paths (in-place)."""
    for rule in rules:
        if "WORKSPACE_DIR" in rule.match:
            rule.match = rule.match.replace("WORKSPACE_DIR", workspace_dir)


def _unresolve_workspace_dir(rules: List[GovernanceRule], workspace_dir: str):
    """Restore actual paths in rules back to WORKSPACE_DIR placeholders."""
    for rule in rules:
        if workspace_dir in rule.match:
            rule.match = rule.match.replace(workspace_dir, "WORKSPACE_DIR")


def _parse_rules(items: Optional[list[dict[str, Any]]]) -> List[GovernanceRule]:
    """Parse a list of GovernanceRule from YAML list."""
    if not items:
        return []
    rules = []
    for item in items:
        if not isinstance(item, dict) or "match" not in item:
            continue
        action_str = item.get("action", "deny")
        try:
            action = GovernanceAction(action_str)
        except ValueError:
            action = GovernanceAction.DENY
        rules.append(GovernanceRule(
            match=item["match"],
            action=action,
            reason=item.get("reason", ""),
            grantee=item.get("grantee", "*"),
            duration=item.get("duration", "permanent"),
            session_id=item.get("session_id"),
        ))
    return rules


def _rule_to_dict(rule: GovernanceRule) -> dict[str, Any]:
    """Serialize a GovernanceRule to dict (for YAML output)."""
    d = {
        "match": rule.match,
        "action": rule.action.value,
    }
    if rule.reason:
        d["reason"] = rule.reason
    if rule.grantee != "*":
        d["grantee"] = rule.grantee
    if rule.duration != "permanent":
        d["duration"] = rule.duration
    if rule.session_id:
        d["session_id"] = rule.session_id
    return d
